# Generated by Django 5.0.4 on 2025-01-02 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="name",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("sport", "Sport"),
                    ("entertainment", "Entertainment"),
                    ("technology", "Technology"),
                    ("fashion", "Fashion"),
                ],
                default="sport",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="username",
            field=models.CharField(
                db_index=True,
                default=datetime.datetime(
                    2025, 1, 2, 0, 23, 4, 343850, tzinfo=datetime.timezone.utc
                ),
                max_length=20,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
