# Generated by Django 5.0.4 on 2025-01-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("sports", "Sports"),
                    ("entertainment", "Entertainment"),
                    ("technology", "Technology"),
                    ("fashion", "Fashion"),
                ],
                default="sports",
                max_length=15,
            ),
        ),
    ]
